-- ~/.config/nvim/lsp/intelephense.lua
---@type vim.lsp.Config
return {
    cmd = { "intelephense", "--stdio" },
    filetypes = { "php", "blade" },
    root_markers = { "composer.json", ".git", "artisan" },
    init_options = {
        licenceKey = nil, -- Add your premium key here if you have one
    },
    settings = {
        intelephense = {
            files = {
                maxSize = 5000000,
                associations = { "*.php", "*.blade.php" },
                exclude = {
                    "**/.git/**",
                    "**/node_modules/**",
                    "**/vendor/**/{Tests,tests}/**",
                    "**/.history/**",
                    "**/storage/**",
                    "**/bootstrap/cache/**",
                },
            },
            stubs = {
                "apache",
                "bcmath",
                "bz2",
                "calendar",
                "com_dotnet",
                "Core",
                "ctype",
                "curl",
                "date",
                "dba",
                "dom",
                "enchant",
                "exif",
                "fileinfo",
                "filter",
                "fpm",
                "ftp",
                "gd",
                "hash",
                "iconv",
                "imap",
                "intl",
                "json",
                "ldap",
                "libxml",
                "mbstring",
                "meta",
                "mysqli",
                "oci8",
                "odbc",
                "openssl",
                "pcntl",
                "pcre",
                "PDO",
                "pdo_ibm",
                "pdo_mysql",
                "pdo_pgsql",
                "pdo_sqlite",
                "pgsql",
                "Phar",
                "posix",
                "pspell",
                "readline",
                "Reflection",
                "session",
                "shmop",
                "SimpleXML",
                "snmp",
                "soap",
                "sockets",
                "sodium",
                "SPL",
                "sqlite3",
                "standard",
                "superglobals",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tidy",
                "tokenizer",
                "xml",
                "xmlreader",
                "xmlrpc",
                "xmlwriter",
                "xsl",
                "Zend OPcache",
                "zip",
                "zlib",
                -- Laravel specific
                "laravel",
            },
            environment = {
                includePaths = {
                    "vendor/laravel/framework/src",
                    "vendor/laravel/laravel",
                },
                phpVersion = "8.2.0",
            },
            completion = {
                insertUseDeclaration = true,
                fullyQualifyGlobalConstantsAndFunctions = false,
                triggerParameterHints = true,
                maxItems = 100,
            },
            format = {
                enable = true,
                braces = "psr12",
            },
            diagnostics = {
                enable = true,
                run = "onType",
            },
        },
    },
}
