[Settings]
gtk-theme-name=Arc-Dark
; gtk-icon-theme-name=hicolor
gtk-icon-theme-name=Papirus
gtk-font-name=Sans 10
gtk-cursor-theme-name=default
gtk-application-prefer-dark-theme=1
gtk-xft-dpi=122880 
