set -g default-terminal "xterm-256color"
set -s escape-time 0

set-option -g status-position bottom
set -g status-left "  #[bold]#S #[default]| "

#plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'vaaleyard/tmux-dotbar'

#unbind
# unbind C-b
unbind d

# set -g prefix "'"
set -g prefix C-b
# bind C-b send-prefix
# bind C-b send-prefix \; display "Prefix clicked"
bind r source-file ~/.tmux.conf \; display "tmux reloaded"
# set-hook -g pane-focus-in 'if-shell "[ #{pane_current_command} = nvim ]" "set -g status off" "set -g status on"'

set-hook -g pane-focus-in 'if-shell "[ #{pane_current_command} = nvim ]" "set -g status off" "set -g status on"'

set -gq allow-passthrough on
set -g base-index 1
set -g renumber-window on
set-option -g status-left-length 40
set -g pane-border-status off

set -g mode-keys vi
bind n copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
#splite panes
bind 'g' split-window -h
bind 'v' split-window -v

# for color
set -g status-style bg=default,fg=default
set -g window-status-format "#I: #W"
set -g window-status-current-format "#I: #W"
set -g window-status-current-style fg=green,bold

set -g status-left "#S | "
set -g status-right ""
set -g window-status-format " #W"
set -g window-status-current-format "*#W"


# switch window
bind -n M-p previous-window
bind -n M-n next-window
# switch session
bind -n M-[ switch-client -p
bind -n M-] switch-client -n

bind-key m set -g status

# kill session
bind-key q confirm-before -p "Kill session? (y/n)" kill-session

#create new window
#new window with the current dircotry
bind-key a new-window -c "#{pane_current_path}"
#new window with home directory
bind-key d new-window -c "$HOME"
bind c kill-window
bind e detach

#create new session
# bind-key S command-prompt -p "Enter session name: " "new-session -s '%%'"
bind-key s command-prompt -p "Enter session name: " "new-session -c $HOME -s '%%'"

# set -g status-right "Uptime: #(~/script/tmux_session_time.sh) | %a %Y-%m-%d %H:%M"

# This is for fuzzy find
bind-key -n C-p run-shell "tmux neww $HOME/script/tmux_sessionaizers.sh"
bind-key -n C-o run-shell "tmux neww ~/script/python_new.py"

#This is must be in last
run-shell '~/.tmux/plugins/tpm/tpm'
