Section "InputClass"
    Identifier "Logitech Wireless Receiver Mouse"
    MatchIsPointer "yes"
    Driver "libinput"
    Option "HighResolutionWheelScrollEnabled" "false"
    Option "ScrollPixelDistance" "50"
EndSection
